import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TodosContextProvider } from "@/context/todosContext";
import store from "@/redux/store";
import { Provider } from "react-redux";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create  App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <TodosContextProvider> */}
      <ReduxProvider>
        <body className={inter.className}>{children}</body>
      </ReduxProvider>
      {/* </TodosContextProvider> */}
    </html>
  );
}
